apiVersion: v1
kind: Service
metadata:
  name: flask-express-app
spec: 
  type: NodePort
  selector:
    app: flask-express-app
    tier: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
