apiVersion: v1
kind: Service
metadata:
  name: flask-express-app
spec:
  type: NodePort
  selector:
    app: flask-express-app
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
    nodePort: 30080
