apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-express-app
spec:
  selector:
    matchLabels:
      app: flask-express-app
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-express-app
        tier: frontend
        track: stable
    spec:
      containers:
        - name: flask-express-container
          image: srilakshmiyannam/flask-app
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
